// <auto-generated />
using System;
using Imobiliare.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Imobiliare.Migrations
{
    [DbContext(typeof(ImobiliareContext))]
    [Migration("20251124205217_Intermediar")]
    partial class Intermediar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Imobiliare.Models.Anunturi", b =>
                {
                    b.Property<int>("ID_Anunt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Anunt"));

                    b.Property<DateTime>("Data_publicare")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ID_Utilizator")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Imagine_anunt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Locatie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Pret")
                        .HasColumnType("numeric");

                    b.HasKey("ID_Anunt");

                    b.HasIndex("ID_Utilizator");

                    b.ToTable("Anunturi");
                });

            modelBuilder.Entity("Imobiliare.Models.Conversatie", b =>
                {
                    b.Property<int>("ID_Conversatie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Conversatie"));

                    b.Property<int?>("AnunturiID_Anunt")
                        .HasColumnType("integer");

                    b.Property<int>("ID_Anunt")
                        .HasColumnType("integer");

                    b.Property<int>("ID_Utilizator_client")
                        .HasColumnType("integer");

                    b.Property<int>("ID_Utilizator_proprietar")
                        .HasColumnType("integer");

                    b.Property<int?>("UtilizatorId")
                        .HasColumnType("integer");

                    b.HasKey("ID_Conversatie");

                    b.HasIndex("AnunturiID_Anunt");

                    b.HasIndex("ID_Utilizator_client");

                    b.HasIndex("ID_Utilizator_proprietar");

                    b.HasIndex("UtilizatorId");

                    b.ToTable("Conversatii");
                });

            modelBuilder.Entity("Imobiliare.Models.Favorite", b =>
                {
                    b.Property<int>("ID_Favorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Favorite"));

                    b.Property<int?>("AnunturiID_Anunt")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data_adaugare")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ID_Anunt")
                        .HasColumnType("integer");

                    b.Property<int?>("ID_Utilizator")
                        .HasColumnType("integer");

                    b.HasKey("ID_Favorite");

                    b.HasIndex("AnunturiID_Anunt");

                    b.HasIndex("ID_Utilizator");

                    b.ToTable("Favorite");
                });

            modelBuilder.Entity("Imobiliare.Models.Formular", b =>
                {
                    b.Property<int>("ID_Formular")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Formular"));

                    b.Property<DateTime>("Data_trimitere")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdUtilizator")
                        .HasColumnType("integer");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subiect")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_Formular");

                    b.HasIndex("IdUtilizator");

                    b.ToTable("Formulare");
                });

            modelBuilder.Entity("Imobiliare.Models.Mesaje", b =>
                {
                    b.Property<int>("ID_Mesaj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Mesaj"));

                    b.Property<int?>("ConversatieID_Conversatie")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ID_Conversatie")
                        .HasColumnType("integer");

                    b.Property<int>("ID_Utilizator_expeditor")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Ora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_Mesaj");

                    b.HasIndex("ConversatieID_Conversatie");

                    b.HasIndex("ID_Utilizator_expeditor");

                    b.ToTable("Mesaje");
                });

            modelBuilder.Entity("Imobiliare.Models.Utilizator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("Data_creare")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("Imagine_profil")
                        .HasColumnType("bytea");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tip_utilizator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Imobiliare.Models.Anunturi", b =>
                {
                    b.HasOne("Imobiliare.Models.Utilizator", "Utilizator")
                        .WithMany("Anunturi")
                        .HasForeignKey("ID_Utilizator")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("Imobiliare.Models.Conversatie", b =>
                {
                    b.HasOne("Imobiliare.Models.Anunturi", "Anunturi")
                        .WithMany("Conversatie")
                        .HasForeignKey("AnunturiID_Anunt");

                    b.HasOne("Imobiliare.Models.Utilizator", "Utilizator_client")
                        .WithMany()
                        .HasForeignKey("ID_Utilizator_client")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Imobiliare.Models.Utilizator", "Utilizator_proprietar")
                        .WithMany()
                        .HasForeignKey("ID_Utilizator_proprietar")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Imobiliare.Models.Utilizator", null)
                        .WithMany("Conversatie")
                        .HasForeignKey("UtilizatorId");

                    b.Navigation("Anunturi");

                    b.Navigation("Utilizator_client");

                    b.Navigation("Utilizator_proprietar");
                });

            modelBuilder.Entity("Imobiliare.Models.Favorite", b =>
                {
                    b.HasOne("Imobiliare.Models.Anunturi", "Anunturi")
                        .WithMany()
                        .HasForeignKey("AnunturiID_Anunt");

                    b.HasOne("Imobiliare.Models.Utilizator", "Utilizator")
                        .WithMany("Favorite")
                        .HasForeignKey("ID_Utilizator")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Anunturi");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("Imobiliare.Models.Formular", b =>
                {
                    b.HasOne("Imobiliare.Models.Utilizator", "Utilizator")
                        .WithMany("Formular")
                        .HasForeignKey("IdUtilizator")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("Imobiliare.Models.Mesaje", b =>
                {
                    b.HasOne("Imobiliare.Models.Conversatie", "Conversatie")
                        .WithMany()
                        .HasForeignKey("ConversatieID_Conversatie");

                    b.HasOne("Imobiliare.Models.Utilizator", "Utilizator_expeditor")
                        .WithMany("Mesaje")
                        .HasForeignKey("ID_Utilizator_expeditor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversatie");

                    b.Navigation("Utilizator_expeditor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Imobiliare.Models.Utilizator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Imobiliare.Models.Utilizator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Imobiliare.Models.Utilizator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Imobiliare.Models.Utilizator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Imobiliare.Models.Anunturi", b =>
                {
                    b.Navigation("Conversatie");
                });

            modelBuilder.Entity("Imobiliare.Models.Utilizator", b =>
                {
                    b.Navigation("Anunturi");

                    b.Navigation("Conversatie");

                    b.Navigation("Favorite");

                    b.Navigation("Formular");

                    b.Navigation("Mesaje");
                });
#pragma warning restore 612, 618
        }
    }
}
